### ISSUE TITLE
Complete all tasks needed to set up a tenant for IEF policies

### ISSUE THREAD

**Issue by mrochon** [mrochon/b2cief-upload#1]
As per [docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications)

**Comment by pacohams** [comment]
hI Marius, thanks for your amazing support, 

i'm a little stuck in run then Setup-B2CMultiTenant.ps1 https://github.com/mrochon/b2csamples/tree/master/Scripts/MultiTenant#upload-custom-policies , because i get error related with the policies,:

**Message: Validation failed: 2 validation error(s) found in policy "B2C_1A_EXTENSIONS" of tenant "xyz.onmicrosoft.com".The following error occurred in orchestration step 3 in user journey "SUSI2" in policy
"B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com": Policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com" makes a reference to TechnicalProfile with id "AAD-UserReadUsingAlternativeSecurityId-NoError"
but neither the policy nor any of its base policies contain such an element.The following error occurred in orchestration step 3 in user journey "SUSI2" in policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com": Policy
"B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com" makes a reference to TechnicalProfile with id "AAD-UserReadUsingAlternativeSecurityId-NoError" but neither the policy nor any of its base policies contain such an
element.The following error occurred in orchestration step 3 in user journey "SUSI2" in policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com": Policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com"
makes a reference to TechnicalProfile with id "AAD-UserReadUsingAlternativeSecurityId-NoError" but neither the policy nor any of its base policies contain such an element.The following error occurred in orchestration step 3 in user
journey "SUSI2" in policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com": Policy "B2C_1A_Extensions" of tenant "xyz.onmicrosoft.com" makes a reference to TechnicalProfile with id
"AAD-UserReadUsingAlternativeSecurityId-NoError" but neither the policy nor any of its base policies contain such an element".**




i try to run the tool  https://github.com/mrochon/b2cief-upload, but i fail, first i try to upload the xml in b2cief-upload/sampleData/LocalAccounts/ but i read that files are only examples, then i try to upload 
https://github.com/mrochon/b2csamples/tree/master/Policies/MultiTenant

but i get the same result, dont upload
this is my script

Connect-AzureAD -TenantId xyz.onmicrosoft.com
$confFile = "C:\dev\ActiveDirecB2C\MROCHON\b2csamples-master\Policies\MultiTenant\appSettings.json"
$source = "C:\dev\ActiveDirecB2C\MROCHON\b2csamples-master\Policies\MultiTenant\"
$dest = "C:\dev\ActiveDirecB2C\MROCHON\b2csamples-master\Policies\MultiTenant\"

.\Upload-IEFPolicies.ps1 Upload-IEFPolicies2 -sourceDirectory $source -configurationFilePath $confFile -updatedSourceDirectory $dest 
first option
user:mail@xyz..onmicrosoft.com
with password
second with the account owner of the azure subscription

thanks for you amazing job

**Comment by mrochon** [comment]
Can you copy the output window listing the sequence in which the PS is trying to upload the policies? It should start with the Base policy, which does define that technical profile (AAD-UserReadUsingAlternativeSecurityId-NoError). Are you perhaps using a different base policy? Perhaps delete you debug folder under your $dest directory to force a complete upload of all policies. If it still does not work and the sequence of upload is Base, followed by Extensions, then check whether your base has the AAD-UserReadUsingAlternativeSecurityId-NoError defined in it. BTW, I usually change my working folder to wherever my source policies are, create a conf.json file there with at least the Prefix property setting and then just run upload-iefpolicies with no parameters. The defaults will use current working folder for source and copy the updated policies into debug/b2cname subfolder of that folder.

**Comment by pacohams** [comment]
Hi Marius, after read carefully i notice that Setup-B2CMultiTenant.ps1 includes creation of policies, then i forgot this step, instead of i register facebook and google policy keys and everything works

thanks
